name: Pull Request
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  biome:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      - name: pnpm install
        run: pnpm install
      - name: biome ci
        run: pnpm exec biome ci --reporter=github .

  proofdict-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: setup pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
      - name: pnpm install
        run: pnpm install
      - name: proofdict test
        run: pnpm run test
