name: Pull Request
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  biome:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: pnpm install
        run: pnpm install
      - name: biome ci
        run: pnpm exec biome ci --reporter=github .

  proofdict-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: pnpm install
        run: pnpm install
      - name: proofdict test
        run: pnpm run test
